{/* app/careers/components/constants.ts */}

import { Position } from './types';

export const positions: Position[] = [
    {
      id: 1,
      title: "Senior Frontend Developer",
      department: "Engineering",
      location: "Remote / Hybrid",
      type: "Full-time",
      experienceRequired: 5,
      salary: "₹18L - ₹24L",
      tags: ["React", "NextJS", "TypeScript"],
      description: "Join our engineering team to build innovative educational platforms",
      datePosted: "Feb 08, 2025",
      workSite: "Up to 50% work from home",
      discipline: "Software Engineering",
      roleType: "Individual Contributor",
      employmentType: "Full-Time",
      jobNumber: "1798395"
    },
    {
      id: 2,
      title: "Science Content Developer",
      department: "Education",
      location: "Remote",
      type: "Full-time",
      experienceRequired: 3,
      salary: "₹12L - ₹15L",
      tags: ["Science", "Content Creation", "Education"],
      description: "Create engaging science content for our interactive platforms",
      datePosted: "Feb 07, 2025",
      workSite: "Remote",
      discipline: "Education",
      roleType: "Individual Contributor",
      employmentType: "Full-Time",
      jobNumber: "1798396"
    },
    {
      id: 3,
      title: "UX/UI Designer",
      department: "Design",
      location: "Remote / Hybrid",
      type: "Full-time",
      experienceRequired: 4,
      salary: "₹14L - ₹20L",
      tags: ["Figma", "Design Systems", "User Research"],
      description: "Design intuitive interfaces for our educational products",
      datePosted: "Feb 06, 2025",
      workSite: "Hybrid",
      discipline: "Design",
      roleType: "Individual Contributor",
      employmentType: "Full-Time",
      jobNumber: "1798397"
    },
    {
      id: 4,
      title: "Educational Technology Specialist",
      department: "Product",
      location: "Remote",
      type: "Full-time",
      experienceRequired: 2,
      salary: "₹11L - ₹14L",
      tags: ["EdTech", "Product Strategy", "User Experience"],
      description: "Shape the future of our educational technology products",
      datePosted: "Feb 06, 2025",
      workSite: "Remote",
      discipline: "Product Management",
      roleType: "Individual Contributor",
      employmentType: "Full-Time",
      jobNumber: "1798398"
    },
    {
      id: 5,
      title: "Backend Engineer",
      department: "Engineering",
      location: "Bangalore",
      type: "Full-time",
      experienceRequired: 4,
      salary: "₹16L - ₹22L",
      tags: ["Node.js", "Python", "MongoDB", "AWS"],
      description: "Build scalable backend systems for our educational platform",
      datePosted: "Feb 05, 2025",
      workSite: "On-site",
      discipline: "Software Engineering",
      roleType: "Individual Contributor",
      employmentType: "Full-Time",
      jobNumber: "1798399"
    },
    {
      id: 6,
      title: "Physics Content Developer",
      department: "Education",
      location: "Remote",
      type: "Part-time",
      experienceRequired: 2,
      salary: "₹6L - ₹8L",
      tags: ["Physics", "Content Writing", "Education"],
      description: "Create engaging physics content for high school students",
      datePosted: "Feb 05, 2025",
      workSite: "Remote",
      discipline: "Education",
      roleType: "Individual Contributor",
      employmentType: "Part-Time",
      jobNumber: "1798400"
    },
    {
      id: 7,
      title: "Product Manager",
      department: "Product",
      location: "Hybrid",
      type: "Full-time",
      experienceRequired: 6,
      salary: "₹25L - ₹35L",
      tags: ["Product Strategy", "Agile", "EdTech"],
      description: "Lead product development for our educational solutions",
      datePosted: "Feb 04, 2025",
      workSite: "Hybrid",
      discipline: "Product Management",
      roleType: "Manager",
      employmentType: "Full-Time",
      jobNumber: "1798401"
    },
    {
      id: 8,
      title: "DevOps Engineer",
      department: "Engineering",
      location: "Remote",
      type: "Full-time",
      experienceRequired: 3,
      salary: "₹14L - ₹20L",
      tags: ["AWS", "Docker", "Kubernetes", "CI/CD"],
      description: "Manage and improve our cloud infrastructure and deployment processes",
      datePosted: "Feb 04, 2025",
      workSite: "Remote",
      discipline: "DevOps",
      roleType: "Individual Contributor",
      employmentType: "Full-Time",
      jobNumber: "1798402"
    },
    {
      id: 9,
      title: "Motion Designer",
      department: "Design",
      location: "Remote",
      type: "Contract",
      experienceRequired: 2,
      salary: "₹8L - ₹12L",
      tags: ["After Effects", "Animation", "Video Editing"],
      description: "Create engaging animations for educational content",
      datePosted: "Feb 03, 2025",
      workSite: "Remote",
      discipline: "Design",
      roleType: "Individual Contributor",
      employmentType: "Contract",
      jobNumber: "1798403"
    },
    {
      id: 10,
      title: "Engineering Manager",
      department: "Engineering",
      location: "Bangalore",
      type: "Full-time",
      experienceRequired: 8,
      salary: "₹35L - ₹45L",
      tags: ["Team Leadership", "Software Architecture", "Agile"],
      description: "Lead and grow our engineering team while driving technical excellence",
      datePosted: "Feb 03, 2025",
      workSite: "On-site",
      discipline: "Software Engineering",
      roleType: "Manager",
      employmentType: "Full-Time",
      jobNumber: "1798404"
    },
    {
      id: 11,
      title: "QA Automation Engineer",
      department: "Engineering",
      location: "Remote",
      type: "Full-time",
      experienceRequired: 3,
      salary: "₹12L - ₹18L",
      tags: ["Selenium", "Cypress", "JavaScript", "Testing"],
      description: "Build and maintain automated test suites for our platform",
      datePosted: "Feb 02, 2025",
      workSite: "Remote",
      discipline: "QA Engineering",
      roleType: "Individual Contributor",
      employmentType: "Full-Time",
      jobNumber: "1798405"
    },
    {
      id: 12,
      title: "Curriculum Developer Lead",
      department: "Education",
      location: "Hybrid",
      type: "Full-time",
      experienceRequired: 6,
      salary: "₹20L - ₹28L",
      tags: ["Curriculum Design", "Education", "Team Leadership"],
      description: "Lead the development of innovative science curricula",
      datePosted: "Feb 02, 2025",
      workSite: "Hybrid",
      discipline: "Education",
      roleType: "Lead",
      employmentType: "Full-Time",
      jobNumber: "1798406"
    },
    {
      id: 13,
      title: "Full Stack Developer",
      department: "Engineering",
      location: "Remote",
      type: "Full-time",
      experienceRequired: 4,
      salary: "₹16L - ₹24L",
      tags: ["React", "Node.js", "MongoDB", "TypeScript"],
      description: "Develop end-to-end solutions for our educational platform",
      datePosted: "Feb 01, 2025",
      workSite: "Remote",
      discipline: "Software Engineering",
      roleType: "Individual Contributor",
      employmentType: "Full-Time",
      jobNumber: "1798407"
    },
    {
      id: 14,
      title: "Technical Content Writer",
      department: "Education",
      location: "Remote",
      type: "Part-time",
      experienceRequired: 2,
      salary: "₹6L - ₹9L",
      tags: ["Technical Writing", "Documentation", "Education"],
      description: "Create technical documentation and learning resources",
      datePosted: "Feb 01, 2025",
      workSite: "Remote",
      discipline: "Content Development",
      roleType: "Individual Contributor",
      employmentType: "Part-Time",
      jobNumber: "1798408"
    }
  ];

export const PAGE_SIZE = 10;