import { Position } from '../types';

export const PAGE_SIZE = 10;

export const positions: Position[] = [
  {
    id: 1,
    title: "Senior Frontend Developer",
    department: "Engineering",
    location: "Remote / Hybrid",
    type: "Full-time",
    experienceRequired: 5,
    salary: "₹18L - ₹24L",
    tags: ["React", "NextJS", "TypeScript"],
    description: "Join our engineering team to build innovative educational platforms",
    datePosted: "Feb 08, 2025",
    workSite: "Up to 50% work from home",
    discipline: "Software Engineering",
    roleType: "Individual Contributor",
    employmentType: "Full-Time",
    jobNumber: "1798395",
    isNew: true
  },
  {
    id: 2,
    title: "UI/UX Designer",
    department: "Design",
    location: "Bangalore, India",
    type: "Full-time",
    experienceRequired: 3,
    salary: "₹12L - ₹18L",
    tags: ["Figma", "Adobe XD", "User Research"],
    description: "Create beautiful and intuitive user interfaces for our products",
    datePosted: "Feb 07, 2025",
    workSite: "Hybrid",
    discipline: "Design",
    roleType: "Individual Contributor",
    employmentType: "Full-Time",
    jobNumber: "1798396",
    isNew: true
  },
  {
    id: 3,
    title: "DevOps Engineer",
    department: "Infrastructure",
    location: "Remote",
    type: "Full-time",
    experienceRequired: 4,
    salary: "₹20L - ₹28L",
    tags: ["AWS", "Docker", "Kubernetes"],
    description: "Manage and optimize our cloud infrastructure and deployment pipelines",
    datePosted: "Feb 06, 2025",
    workSite: "Remote",
    discipline: "DevOps",
    roleType: "Individual Contributor",
    employmentType: "Full-Time",
    jobNumber: "1798397",
    isNew: true
  },
  {
    id: 4,
    title: "Product Manager",
    department: "Product",
    location: "Mumbai, India",
    type: "Full-time",
    experienceRequired: 6,
    salary: "₹25L - ₹35L",
    tags: ["Product Strategy", "Agile", "Data Analysis"],
    description: "Lead product development and strategy for our core platforms",
    datePosted: "Feb 05, 2025",
    workSite: "In-office",
    discipline: "Product Management",
    roleType: "Manager",
    employmentType: "Full-Time",
    jobNumber: "1798398",
    isNew: false
  },
  {
    id: 5,
    title: "Backend Developer",
    department: "Engineering",
    location: "Pune, India",
    type: "Full-time",
    experienceRequired: 3,
    salary: "₹14L - ₹20L",
    tags: ["Node.js", "PostgreSQL", "Redis"],
    description: "Develop and maintain scalable backend services",
    datePosted: "Feb 05, 2025",
    workSite: "Hybrid",
    discipline: "Software Engineering",
    roleType: "Individual Contributor",
    employmentType: "Full-Time",
    jobNumber: "1798399",
    isNew: false
  },
  {
    id: 6,
    title: "Data Scientist",
    department: "Analytics",
    location: "Remote",
    type: "Full-time",
    experienceRequired: 4,
    salary: "₹16L - ₹25L",
    tags: ["Python", "ML", "TensorFlow"],
    description: "Build and deploy machine learning models for our products",
    datePosted: "Feb 04, 2025",
    workSite: "Remote",
    discipline: "Data Science",
    roleType: "Individual Contributor",
    employmentType: "Full-Time",
    jobNumber: "1798400",
    isNew: false
  },
  {
    id: 7,
    title: "Technical Writer",
    department: "Documentation",
    location: "Hyderabad, India",
    type: "Contract",
    experienceRequired: 2,
    salary: "₹8L - ₹12L",
    tags: ["Documentation", "API", "Technical Writing"],
    description: "Create comprehensive documentation for our technical products",
    datePosted: "Feb 04, 2025",
    workSite: "Hybrid",
    discipline: "Technical Writing",
    roleType: "Individual Contributor",
    employmentType: "Contract",
    jobNumber: "1798401",
    isNew: false
  },
  {
    id: 8,
    title: "Engineering Manager",
    department: "Engineering",
    location: "Bangalore, India",
    type: "Full-time",
    experienceRequired: 8,
    salary: "₹35L - ₹45L",
    tags: ["Team Management", "Architecture", "Agile"],
    description: "Lead and mentor a team of talented engineers",
    datePosted: "Feb 03, 2025",
    workSite: "In-office",
    discipline: "Engineering Management",
    roleType: "Manager",
    employmentType: "Full-Time",
    jobNumber: "1798402",
    isNew: false
  },
  {
    id: 9,
    title: "QA Engineer",
    department: "Quality Assurance",
    location: "Chennai, India",
    type: "Full-time",
    experienceRequired: 3,
    salary: "₹10L - ₹15L",
    tags: ["Selenium", "TestNG", "Automation"],
    description: "Ensure product quality through automated and manual testing",
    datePosted: "Feb 03, 2025",
    workSite: "Hybrid",
    discipline: "Quality Assurance",
    roleType: "Individual Contributor",
    employmentType: "Full-Time",
    jobNumber: "1798403",
    isNew: false
  },
  {
    id: 10,
    title: "Mobile Developer",
    department: "Engineering",
    location: "Remote",
    type: "Full-time",
    experienceRequired: 4,
    salary: "₹16L - ₹22L",
    tags: ["React Native", "iOS", "Android"],
    description: "Build cross-platform mobile applications",
    datePosted: "Feb 02, 2025",
    workSite: "Remote",
    discipline: "Mobile Development",
    roleType: "Individual Contributor",
    employmentType: "Full-Time",
    jobNumber: "1798404",
    isNew: false
  },
  {
    id: 11,
    title: "Solutions Architect",
    department: "Architecture",
    location: "Bangalore, India",
    type: "Full-time",
    experienceRequired: 7,
    salary: "₹30L - ₹45L",
    tags: ["System Design", "Cloud Architecture", "Technical Leadership"],
    description: "Design and architect scalable solutions for enterprise clients",
    datePosted: "Feb 02, 2025",
    workSite: "Hybrid",
    discipline: "Architecture",
    roleType: "Technical Leader",
    employmentType: "Full-Time",
    jobNumber: "1798405",
    isNew: false
  },
  {
    id: 12,
    title: "Junior Frontend Developer",
    department: "Engineering",
    location: "Pune, India",
    type: "Full-time",
    experienceRequired: 1,
    salary: "₹6L - ₹10L",
    tags: ["HTML", "CSS", "JavaScript"],
    description: "Join our frontend team and learn from experienced developers",
    datePosted: "Feb 01, 2025",
    workSite: "In-office",
    discipline: "Software Engineering",
    roleType: "Individual Contributor",
    employmentType: "Full-Time",
    jobNumber: "1798406",
    isNew: false
  },
  {
    id: 13,
    title: "Security Engineer",
    department: "Security",
    location: "Remote",
    type: "Full-time",
    experienceRequired: 5,
    salary: "₹20L - ₹30L",
    tags: ["Security", "Penetration Testing", "Compliance"],
    description: "Ensure the security of our applications and infrastructure",
    datePosted: "Feb 01, 2025",
    workSite: "Remote",
    discipline: "Security",
    roleType: "Individual Contributor",
    employmentType: "Full-Time",
    jobNumber: "1798407",
    isNew: false
  },
  {
    id: 14,
    title: "Scrum Master",
    department: "Project Management",
    location: "Mumbai, India",
    type: "Full-time",
    experienceRequired: 4,
    salary: "₹15L - ₹22L",
    tags: ["Agile", "Scrum", "Team Management"],
    description: "Facilitate agile processes and remove team impediments",
    datePosted: "Jan 31, 2025",
    workSite: "Hybrid",
    discipline: "Project Management",
    roleType: "Manager",
    employmentType: "Full-Time",
    jobNumber: "1798408",
    isNew: false
  },
  {
    id: 15,
    title: "Database Administrator",
    department: "Infrastructure",
    location: "Hyderabad, India",
    type: "Full-time",
    experienceRequired: 6,
    salary: "₹18L - ₹28L",
    tags: ["PostgreSQL", "MongoDB", "Database Management"],
    description: "Manage and optimize database performance and reliability",
    datePosted: "Jan 31, 2025",
    workSite: "In-office",
    discipline: "Database Administration",
    roleType: "Individual Contributor",
    employmentType: "Full-Time",
    jobNumber: "1798409",
    isNew: false
  },
  {
    id: 16,
    title: "Technical Support Engineer",
    department: "Customer Support",
    location: "Chennai, India",
    type: "Full-time",
    experienceRequired: 2,
    salary: "₹8L - ₹12L",
    tags: ["Customer Support", "Troubleshooting", "Technical Support"],
    description: "Provide technical support to our enterprise customers",
    datePosted: "Jan 30, 2025",
    workSite: "Hybrid",
    discipline: "Technical Support",
    roleType: "Individual Contributor",
    employmentType: "Full-Time",
    jobNumber: "1798410",
    isNew: false
  },
  {
    id: 17,
    title: "Machine Learning Engineer",
    department: "AI/ML",
    location: "Remote",
    type: "Full-time",
    experienceRequired: 4,
    salary: "₹20L - ₹30L",
    tags: ["Python", "Deep Learning", "MLOps"],
    description: "Develop and deploy machine learning models at scale",
    datePosted: "Jan 30, 2025",
    workSite: "Remote",
    discipline: "Machine Learning",
    roleType: "Individual Contributor",
    employmentType: "Full-Time",
    jobNumber: "1798411",
    isNew: false
  },
  {
    id: 18,
    title: "Performance Engineer",
    department: "Engineering",
    location: "Bangalore, India",
    type: "Full-time",
    experienceRequired: 5,
    salary: "₹18L - ₹25L",
    tags: ["Performance Testing", "Optimization", "Monitoring"],
    description: "Optimize application performance and resource utilization",
    datePosted: "Jan 29, 2025",
    workSite: "Hybrid",
    discipline: "Performance Engineering",
    roleType: "Individual Contributor",
    employmentType: "Full-Time",
    jobNumber: "1798412",
    isNew: false
  },
  {
    id: 19,
    title: "Cloud Engineer",
    department: "Infrastructure",
    location: "Remote",
    type: "Contract",
    experienceRequired: 3,
    salary: "₹15L - ₹22L",
    tags: ["AWS", "Azure", "Cloud Infrastructure"],
    description: "Manage and optimize our cloud infrastructure",
    datePosted: "Jan 29, 2025",
    workSite: "Remote",
    discipline: "Cloud Engineering",
    roleType: "Individual Contributor",
    employmentType: "Contract",
    jobNumber: "1798413",
    isNew: false
  },
  {
    id: 20,
    title: "Frontend Tech Lead",
    department: "Engineering",
    location: "Pune, India",
    type: "Full-time",
    experienceRequired: 7,
    salary: "₹25L - ₹35L",
    tags: ["React", "Architecture", "Team Leadership"],
    description: "Lead frontend development and mentor team members",
    datePosted: "Jan 28, 2025",
    workSite: "Hybrid",
    discipline: "Software Engineering",
    roleType: "Technical Leader",
    employmentType: "Full-Time",
    jobNumber: "1798414",
    isNew: false
  }
].filter(Boolean);

export const FILTER_CATEGORIES = {
  EXPERIENCE: 'Experience',
  WORK_SITE: 'Work Site',
  PROFESSION: 'Profession',
  DISCIPLINE: 'Discipline',
  ROLE_TYPE: 'Role Type',
  EMPLOYMENT_TYPE: 'Employment Type'
} as const;

export const WORK_SITES = {
  REMOTE: 'Remote',
  HYBRID: 'Hybrid',
  ONSITE: 'On-site'
} as const;

export const ROLE_TYPES = {
  IC: 'Individual Contributor',
  LEAD: 'Lead',
  MANAGER: 'Manager'
} as const;

export const EMPLOYMENT_TYPES = {
  FULL_TIME: 'Full-Time',
  PART_TIME: 'Part-Time',
  CONTRACT: 'Contract'
} as const;